#!/usr/bin/env python
# Script function: takes the condition-specific timing files generated by optimize
# and puts them into a single document, good for experimental presentation software

# USED FOR CARAT -- SPONT
import numpy as np
import sys
import pandas as pd

# create function that reshapes the timing files
def timing_type8(data, num):
	df=pd.read_table(data, sep=' ', header=None)
	df=df.transpose()
	df=df.drop(8)
	df=df.rename(index=str, columns={0:"Onset Time"})
	df['Type']=num
	return df;

# load and reshape the timing files
p="./Posed.1D"
P = timing_type8(p,1)

r="./Regulated.1D"
R = timing_type8(r,2)

s="./Spontaneous.1D"
S=timing_type8(s,3)

# put all reshaped timing files together
times = [P, R, S]
result = pd.concat(times)
result = result.sort_values(by=['Onset Time'])
result = result.reset_index()
result = result.drop('index', axis=1)

# add a column with trial type names
trialtypes = {1: "Posed", 2: "Regulated", 3: "Spontaneous"}
result['TrialType'] = result['Type'].map(trialtypes)

# write to csv
result.to_csv('SPONT_timings.csv', index=False, sep=',')
